// PROMPT: Imagine you are a senior software engineer. You have experience in React and API development.
// As a user, I want to receive simple, AI-generated suggestions based on my eating habits, so that I can get ideas for improving my diet.
// Acceptance Criteria:
// When I visit the dashboard, I see a separate section within a box.
// The tip is a simple suggestion generated by an LLM based on my historical data
// (e.g., "It looks like your protein intake was low yesterday. Consider adding a food like chicken or beans today!").
// Give me a plan for how you want to generate this.
// Generate a component called ImagePrompt that allows the user to upload an image and recognize food items in it.

// This generated AISuggestions.css. This additionally generated ai.js in the backend to generate the suggestions. However, that code was fully rewritten.


import { useState, useEffect } from 'react';
import { getAISuggestions } from '../api';
import './AISuggestions.css';

function AISuggestions({ selectedDate }) {
    const [suggestions, setSuggestions] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    const fetchSuggestions = async () => {
        setLoading(true);
        setError(null);
        try {
            const data = await getAISuggestions(selectedDate);
            setSuggestions(data);
        } catch (err) {
            console.error('Failed to fetch AI suggestions:', err.message);
            setError(err.message);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchSuggestions();
    }, [selectedDate]);

    return (
        <div className="ai-suggestions">
            <div className="ai-suggestions-header">
                <h2 className="ai-suggestions-h2">AI Suggestions</h2>
                <button
                    className="ai-refresh-button"
                    onClick={fetchSuggestions}
                    disabled={loading}
                    title="Refresh suggestions"
                >
                    {loading ? (
                        <span className="material-symbols-outlined" aria-hidden>hourglass_empty</span>
                    ) : (
                        <span className="material-symbols-outlined" aria-hidden>refresh</span>
                    )}
                </button>
            </div>
            <div className="ai-suggestions-textbox">
                {loading ? (
                    <p>Loading suggestions...</p>
                ) : error ? (
                    <p className="ai-error">Error: {error}</p>
                ) : Array.isArray(suggestions?.suggestions) ? (
                    <div className="ai-suggestions-list">
                        <ul>
                            {suggestions.suggestions.map((it, idx) => (
                                <li key={idx} className="ai-suggestion-item">
                                    <span className="ai-suggestion-name">{it.name}. </span>
                                    <span className="ai-suggestion-rationale">{it.rationale}</span>
                                </li>
                            ))}
                        </ul>
                        {suggestions.note && <div className="ai-suggestion-note">{suggestions.note}</div>}
                    </div>
                ) : (
                    <p>No suggestions available</p>
                )}
            </div>
        </div>
    );
}

export default AISuggestions;